import _ from 'lodash'
import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Link from 'next/link'
import XCanvas from '../../@components/x/x-canvas/component'
import {
  ContactShadows,
  Edges,
  Environment,
  Float,
  OrbitControls,
  Select,
  Sky,
} from '@react-three/drei'
import { Suspense } from 'react'
import { useGlobalStore } from '../../@helpers/x-store'
import { useGUIControls } from '../../@components/x/x-gui/component'
import { RhombicDodecaedron } from '../../@components/x/x-shapes/rhombic_dodecahedron'
import { XPage } from '../type'
import { motion } from 'framer-motion'

function TrackedMesh({
  color = 'white',
  thickness = 2,
  roughness = 0.65,
  envMapIntensity = 1,
  transmission = 0,
  metalness = 0,
  ...props
}) {
  const [storeGUI] = useGlobalStore((state) => [state.guiStore])
  const [store, { ...materialProps }] = useGUIControls({
    color: { value: color },
    roughness: { value: roughness, min: 0, max: 1 },
    thickness: { value: thickness, min: -10, max: 10 },
    envMapIntensity: { value: envMapIntensity, min: 0, max: 10 },
    transmission: { value: transmission, min: 0, max: 1 },
    ...(metalness !== undefined && {
      metalness: { value: metalness, min: 0, max: 1 },
    }),
  })
  const isSelected = !!store && store?.storeId === storeGUI?.storeId
  return (
    <RhombicDodecaedron {...props} userData={{ store }}>
      <meshPhysicalMaterial {...materialProps} />
      <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
        <meshBasicMaterial transparent color='#333' depthTest={false} />
      </Edges>
    </RhombicDodecaedron>
  )
}

const Home: XPage = () => {
  const { t, i18n } = useTranslation('common')
  const [setGUIStore] = useGlobalStore((state) => [state.setGUIStore])
  const [selected] = useGlobalStore((state) => [state.selectedCanvas])
  const perfData = useGlobalStore((state) => state.perfData)

  return (
    <motion.div exit={{ opacity: 0 }}>
      <Head>
        <title>r3f-basic</title>
        <meta name='description' content='Generated by r3f-basic' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ margin: 'auto', padding: '50px 10px' }}>
        <h1>{t(`lang`)}</h1>
        <Link href='/' locale={i18n.language === 'fr' ? 'en' : 'fr'}>
          Switch language
        </Link>
        <Link href='/test'>To Test</Link>
        <XCanvas
          dpr={[1, 2]}
          orthographic
          camera={{ position: [5, 6, 15], zoom: 40, fov: 75 }}
        >
          <ambientLight />
          <Suspense fallback={null}>
            <Select
              multiple
              box
              onChange={(obj) => {
                setGUIStore(obj[0]?.userData?.store)
              }}
            >
              <Float
                speed={5}
                rotationIntensity={1}
                floatIntensity={0.5}
                floatingRange={[0, 1.5]}
              >
                <TrackedMesh
                  position={[-2, 0.5, 0.5]}
                  color='#4B9D7D'
                  metalness={1}
                  roughness={0}
                />
              </Float>
              <Float
                speed={10}
                rotationIntensity={2}
                floatIntensity={0.5}
                floatingRange={[0, 2]}
              >
                <TrackedMesh color='#58BD95' roughness={1} />
              </Float>
              <Float speed={3} floatIntensity={0.5} floatingRange={[0, 2]}>
                <TrackedMesh position={[2, 0.5, 0.5]} color='#70EBBA' />
              </Float>
              <Float
                speed={2}
                rotationIntensity={0.2}
                floatIntensity={0.5}
                floatingRange={[0, 1]}
              >
                <TrackedMesh
                  position={[0, 0.5, 2]}
                  color='#E3DAC9'
                  transmission={1}
                  roughness={0}
                />
              </Float>
            </Select>
          </Suspense>
          <Environment preset='city' />
          <OrbitControls
            makeDefault
            rotateSpeed={2}
            minPolarAngle={0}
            maxPolarAngle={Math.PI / 2.5}
          />
          <Sky />
          <ContactShadows
            position={[0, -1.2, 0]}
            opacity={0.25}
            scale={10}
            blur={1.5}
            far={1.5}
          />
        </XCanvas>
        <div>
          Selected Canvas: {selected || 'Select a canvas'}
          <br />
          Data:
          <br />
          {perfData?.log?.fps || ''}
        </div>
      </main>
    </motion.div>
  )
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
    },
  }
}
export default Home
