import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import styles from '../@styles/Home.module.css'
import Link from 'next/link'
import XCanvas from '../@components/x-canvas/x-canvas'
import {
  Edges,
  Environment,
  OrbitControls,
  Select,
  Sky,
  useCursor,
} from '@react-three/drei'
import { Suspense } from 'react'
import { useGlobalStore } from '../@helpers/store'
import { useGUIControls } from '../@components/x-gui/x-gui'

function Cube({
  color = 'white',
  thickness = 2,
  roughness = 0.65,
  envMapIntensity = 1,
  transmission = 0,
  metalness = 0,
  ...props
}) {
  const [storeGUI] = useGlobalStore((state) => [state.guiStore])
  const [store, materialProps] = useGUIControls({
    color: { value: color },
    roughness: { value: roughness, min: 0, max: 1 },
    thickness: { value: thickness, min: -10, max: 10 },
    envMapIntensity: { value: envMapIntensity, min: 0, max: 10 },
    transmission: { value: transmission, min: 0, max: 1 },
    ...(metalness !== undefined && {
      metalness: { value: metalness, min: 0, max: 1 },
    }),
  })
  const isSelected = !!store && store?.storeId === storeGUI?.storeId
  return (
    <mesh {...props} userData={{ store }}>
      <boxGeometry />
      <meshPhysicalMaterial {...materialProps} />
      <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
        <meshBasicMaterial transparent color='#333' depthTest={false} />
      </Edges>
    </mesh>
  )
}

const Home: NextPage = () => {
  const { t, i18n } = useTranslation('common')
  const [setGUIStore] = useGlobalStore((state) => [state.setGUIStore])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>{t(`test`)}</h1>
        <Link href='/' locale='fr'>
          To /fr/another
        </Link>
        <button> test </button>
        <XCanvas
          dpr={[1, 2]}
          orthographic
          camera={{ position: [-10, 10, 10], zoom: 100 }}
        >
          <pointLight position={[10, 10, 10]} />
          <Suspense fallback={null}>
            <Select
              multiple
              box
              onChange={(obj) => {
                setGUIStore(obj[0]?.userData?.store)
              }}
            >
              <Cube
                scale={0.9}
                position={[0, 0, 0]}
                color='#eb8686'
                envMapIntensity={2}
              />
              <Cube
                scale={0.9}
                position={[-1, 0, 0]}
                color='orange'
                transmission={1}
                thickness={-2}
                envMapIntensity={5}
              />
              <Cube
                scale={[1, 0.9, 0.9]}
                position={[0.05, 0, 1]}
                color='aquamarine'
                metalness={0}
              />
            </Select>
          </Suspense>
          <Environment preset='city' />
          <OrbitControls
            makeDefault
            rotateSpeed={2}
            minPolarAngle={0}
            maxPolarAngle={Math.PI / 2.5}
          />
          <Sky />
        </XCanvas>
        <XCanvas
          dpr={[1, 2]}
          orthographic
          camera={{ position: [-10, 10, 10], zoom: 100 }}
        >
          <pointLight position={[10, 10, 10]} />
          <Suspense fallback={null}>
            <Select
              multiple
              box
              onChange={(obj) => {
                setGUIStore(obj[0]?.userData?.store)
              }}
            >
              <Cube
                scale={[1, 0.9, 0.9]}
                position={[0.05, 0, 1]}
                color='aquamarine'
                metalness={0}
              />
            </Select>
          </Suspense>
          <Environment preset='city' />
          <OrbitControls
            makeDefault
            rotateSpeed={2}
            minPolarAngle={0}
            maxPolarAngle={Math.PI / 2.5}
          />
          <Sky />
        </XCanvas>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
    },
  }
}
export default Home
